"""Add active attr in user

Revision ID: 68952eeb291b
Revises: b58c89791d5e
Create Date: 2024-07-23 19:49:17.604259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68952eeb291b'
down_revision = 'b58c89791d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
